### PR TITLE
Use playwright instead of puppeteer for browser

### PR DESCRIPTION
**Pull request by mitchhymel**
This is a fix for issue #39 . It seems that Tiktok is able to detect puppeteer launched instances and so signatures generated through such windows are not valid. I was able to get valid signatures using playwright.

Side note: I don't know if there is a playwright equivalent of puppeteer-extra-plugin-stealth or if it is (or will be) needed with playwright, but I can confirm that things are working right now.

### CODE REVIEW

**Comment by nuqz** [comment]
@mitchhymel Hello. I've been using the same algorithm to get signatures in my python code. It worked for a while, but stopped today. I decided to try this package. The signature is generated, but not generated correctly. However, if I run the same code in a regular browser, then it works.

Thank you a lot for your work. It turns out the matter is in the client (browser). Can you give me some advice on how to do the same in Python (`pyppeteer` and `requests-html` packages)? Well, at least hint at what is the key (for this situation) difference between `puppeteer` and `playwright`.

**Comment by kicks66** [comment]
I've tested the above from my server with both m.tiktok and t.tiktok links (using the same code that was working for the puppeteer version) and using playwrite im getting back empty 200s still.

I am getting signatures generated, but those signatures dont produce results in the requests.

**Comment by mitchhymel** [comment]
Weird. I'm able to generate valid signatures to get non empty results. Then it must be as @nuqz  suggested and has something to do with the browser - not the library we're using to launch the browser. I'll have to investigate a bit more.

**Comment by anpato** [comment]
Tiktok did change their service urls, signatures are still working for me.

Here's a list:
Videos:https://m.tiktok.com/api/item_list/?count=30&id=${tiktokId}&type=1&secUid=${secUid}&maxCursor=0&minCursor=0&sourceType=8&appId=1233&region=US&language=en&verifyFp=

Discover: https://m.tiktok.com/node/share/discover?noUser=0&userId=${tiktokId}&userCount=30&scene=15&verifyFp=

User Data: https://m.tiktok.com/api/user/detail/?uniqueId=${uniqueIdentifier}&language=en&verifyFp=

**Comment by kicks66** [comment]
Their website seems to have started to use the `verifyFp` property:

https://m.tiktok.com/node/share/discover?noUser=0&userId=6810109699146630150&userCount=30&scene=15&verifyFp=verify_ka71pqod_AnLTlcyb_lBHL_4YQQ_BeGk_REns0ahD7mao&_signature=axZbTgAgEBmfKCsjcXvjtmsWWlAADWv

This works using the current signature generator, but has a new verify parameter in.

**Comment by nuqz** [comment]
@kicks66 Thank you for the hint. I also noticed that this parameter began to be used, its value is taken from cookie with `s_v_web_id` key. I deleted this key in the browser and looked at all the requests on a page, none of them set this key. I think the value is calculated using JS on a page. However, I tried to sign the URL both with this parameter and without it in a regular browser, both options work.

@carcabot Thank you for the suggestion. I tried 2 different proxies and one VPN, but neither of these helped.

**Upd** When I launched the browser in not headless mode, I noticed that the page fails to load properly.

Here is output:
Here is console output

I am very confused. Even though the scripts on the page are not being executed properly, I was able to generate a valid signature and get the result from the API directly in the `puppeteer` browser instance. But I can not get the result with signed URL in any other client. I can only assume that some necessary cookie is missing.

Here's short JS snippet to reproduce:

```
b = Object();

window.webpackJsonp
    .filter(x => typeof x[1]['duD4'] !== 'undefined')
    .forEach(x => x[1]['duD4'](null, b));

sign_url = url => url + '&_signature=' + b.sign({ url });
verify = url => {
    signed_url = sign_url(url);
    console.log(signed_url);
    return fetch(signed_url)
        .then(response => response.json())
        .then(json => console.log(json))
        .catch(err => console.error(err))
}
```

I think that it will be easier for me to use the API in this way (execute the necessary code immediately in the browser and return the necessary result).

Once again, thank you all, I don’t know what I would do without you.

**Comment by andrearama** [comment]
Hi @nuqz , I am also getting the problem you are having in the last post, that is on several TikTok pages there is not any contect (acutally this is well seen with normal accounts and tag searches pages. Other pages like "discover" work). 
Do you have some work around for this problem? I am trying using other tools, such as selenium, but this problem persists.

@mitchhymel I did try to run your version (inserting the command `node listen.js
`  and then the curl one)  but keep getting this error:

Received url: https://m.tiktok.com/share/item/list?secUid=&id=&type=5&count=30&minCursor=0&maxCursor=0&shareUid=
(node:31422) UnhandledPromiseRejectionWarning: Error: Protocol error (Playwright.createContext): Browser has been closed.
    at /home/andrea/Downloads/New-tiktok-signature/new/tiktok-signature/node_modules/playwright-core/lib/webkit/wkConnection.js:102:63
    at new Promise (<anonymous>)
    at WKSession.send (/home/andrea/Downloads/New-tiktok-signature/new/tiktok-signature/node_modules/playwright-core/lib/webkit/wkConnection.js:101:16)
    at WKBrowser.newContext (/home/andrea/Downloads/New-tiktok-signature/new/tiktok-signature/node_modules/playwright-core/lib/webkit/wkBrowser.js:65:65)
    at WKBrowser.<anonymous> (/home/andrea/Downloads/New-tiktok-signature/new/tiktok-signature/node_modules/playwright-core/lib/helper.js:64:31)
    at Signer.init (/home/andrea/Downloads/New-tiktok-signature/new/tiktok-signature/index.js:48:39)
    at async IncomingMessage.<anonymous> (/home/andrea/Downloads/New-tiktok-signature/new/tiktok-signature/listen.js:26:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31422) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any idea why this keep happening?

Thanks to all for the help and time!

**Comment by mitchhymel** [comment]
I'm going to close this PR as it's clear the issue isn't the use of puppeteer vs playwright, but something else, so it doesn't make sense to merge this. Feel free to continue discussion at issue #39

**Pull request closed without merging**
